# Generated by Django 3.0.3 on 2020-03-01 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hj_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.CharField(max_length=9)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=6)),
                ('count', models.IntegerField()),
                ('submit_user', models.ForeignKey(default='离职', on_delete=django.db.models.deletion.SET_DEFAULT, to='queryorder.hj_user')),
            ],
        ),
    ]
