# Generated by Django 3.0.3 on 2020-03-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queryorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='submit_user',
        ),
        migrations.DeleteModel(
            name='hj_user',
        ),
        migrations.DeleteModel(
            name='orders',
        ),
    ]
